import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:mshtsht/authpage.dart';
import 'package:mshtsht/themes/light_mode.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'auth/auth_repository.dart';
import 'auth/auth_bloc.dart';
//import 'auth/auth_event.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize SharedPreferences

  // Create repository

  // Run the app with BlocProvider
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: AuthPage(),
      theme: lightTheme,
    );
  }

  // android   1:826279281337:android:9e8b7c234c53c98de41168
  // ios       1:826279281337:ios:e7f74549f4d9bbf4e41168
  // macos     1:826279281337:ios:e7f74549f4d9bbf4e41168// android   1:826279281337:android:9e8b7c234c53c98de41168
  // ios       1:826279281337:ios:e7f74549f4d9bbf4e41168
  // macos     1:826279281337:ios:e7f74549f4d9bbf4e41168
}
