import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:mshtsht/auth/auth_bloc.dart';
import 'package:mshtsht/auth/auth_event.dart';
import 'package:mshtsht/authpage.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => AuthBloc()..add(AuthCheckRequested()),
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'BLoC Auth Demo',
        home: AuthPage(),
      ),
    );
  }
}

  // android   1:826279281337:android:9e8b7c234c53c98de41168
  // ios       1:826279281337:ios:e7f74549f4d9bbf4e41168
  // macos     1:826279281337:ios:e7f74549f4d9bbf4e41168// android   1:826279281337:android:9e8b7c234c53c98de41168
  // ios       1:826279281337:ios:e7f74549f4d9bbf4e41168
  // macos     1:826279281337:ios:e7f74549f4d9bbf4e41168